null
---
- ansible.builtin.file:
    mode: '0755'
    path: /etc/grafana/provisioning/{{ item }}
    state: directory
  become: true
  loop:
  - dashboards
  - datasources
  name: Create provisioning directory structure
- ansible.builtin.copy:
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml
    mode: '0644'
    src: provisioning/dashboards.yml
  become: true
  name: Copy dashboard provisioning config
- ansible.builtin.copy:
    dest: /etc/grafana/provisioning/datasources/datasources.yml
    mode: '0644'
    src: provisioning/datasources.yml
  become: true
  name: Copy datasource provisioning config
- ansible.builtin.copy:
    dest: /etc/grafana/provisioning/dashboards/default.json
    mode: '0644'
    src: dashboards/default.json
  become: true
  name: Copy default dashboard JSON
