null
---
- ansible.builtin.file:
    mode: '0755'
    path: /opt/threatfeeds
    state: directory
  become: true
  name: Ensure threat feed sync script directory exists
- ansible.builtin.copy:
    dest: /opt/threatfeeds/sync-threatfeeds.sh
    mode: '0750'
    src: sync-threatfeeds.sh
  become: true
  name: Copy threat feed sync script
- ansible.builtin.command:
    cmd: /opt/threatfeeds/sync-threatfeeds.sh
  become: true
  changed_when: false
  name: Run threat feed sync script
  notify: Reload unbound
- ansible.builtin.cron:
    hour: '2'
    job: /opt/threatfeeds/sync-threatfeeds.sh
    minute: '0'
    name: Daily Threat Feed Sync
    user: root
  name: Add cron job to sync feeds daily
