- ansible.builtin.template:
    dest: /etc/keepalived/keepalived.conf
    group: root
    mode: '0644'
    owner: root
    src: keepalived.conf.j2
  name: Deploy Keepalived configuration
- ansible.builtin.service:
    enabled: true
    name: keepalived
    state: restarted
  name: Enable and start Keepalived
