- ansible.builtin.template:
    dest: /etc/unbound/ipv6-dns-rules.conf
    mode: '0644'
    src: ipv6-dns-rules.conf.j2
  name: Ensure IPv6 DNS security policies are defined
- ansible.builtin.lineinfile:
    insertafter: EOF
    line: 'include: /etc/unbound/ipv6-dns-rules.conf'
    path: /etc/unbound/unbound.conf
    regexp: ^include:.*ipv6-dns-rules\.conf
  name: Include IPv6 rules in main Unbound config
