---
- name: Deploy nfcapd systemd unit
  ansible.builtin.template:
    src: nfcapd.service.j2
    dest: /etc/systemd/system/nfcapd.service
    mode: '0644'

- name: Enable and start nfcapd
  ansible.builtin.systemd:
    name: nfcapd
    enabled: true
    state: started
    daemon_reload: true
