- ansible.builtin.template:
    dest: /etc/systemd/system/nfcapd.service
    mode: '0644'
    src: nfcapd.service.j2
  name: Deploy nfcapd systemd unit
- ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: nfcapd
    state: started
  name: Enable and start nfcapd
