- ansible.builtin.package:
    name:
    - auditd
    - audispd-plugins
    state: present
  name: Ensure required packages are installed for AD log auditing
- ansible.builtin.service:
    enabled: true
    name: auditd
    state: started
  name: Enable and start auditd
