- ansible.builtin.template:
    dest: /usr/local/bin/ad-log-parser.sh
    mode: '0755'
    src: ad-log-parser.sh.j2
  name: Deploy AD log parsing script
- ansible.builtin.cron:
    hour: '*'
    job: /usr/local/bin/ad-log-parser.sh >> /var/log/ad-log-parser.log 2>&1
    minute: '0'
    name: Parse AD Logs Hourly
  name: Setup cronjob for AD log parser
