- ansible.builtin.uri:
    return_content: true
    url: http://localhost:3000/login
  name: Check Grafana web UI is available
  register: grafana_status
- ansible.builtin.assert:
    fail_msg: "\u274C Grafana web UI not reachable"
    success_msg: "\u2705 Grafana web UI is reachable"
    that:
    - grafana_status.status == 200
  name: Assert Grafana login page loaded
