- ansible.builtin.uri:
    return_content: true
    url: http://localhost:9090/-/healthy
  name: Query Prometheus health endpoint
  register: prometheus_health
- ansible.builtin.assert:
    fail_msg: "\u274C Prometheus health check failed"
    success_msg: "\u2705 Prometheus is healthy"
    that:
    - '''Prometheus is Healthy'' in prometheus_health.content or prometheus_health.status
      == 200'
  name: Assert Prometheus is healthy
