- ansible.builtin.service_facts: null
  name: Verify Unbound service is running
- ansible.builtin.assert:
    fail_msg: "\u274C Unbound is not running"
    success_msg: "\u2705 Unbound is running"
    that:
    - ansible_facts.services['unbound.service'].state == 'running'
  name: Assert Unbound is active
