- ansible.builtin.template:
    dest: /etc/unbound/unbound-blocklist.conf
    group: root
    mode: '0644'
    owner: root
    src: unbound-blocklist.conf.j2
  name: Deploy Unbound blocklist configuration
- ansible.builtin.lineinfile:
    line: 'include: "/etc/unbound/unbound-blocklist.conf"'
    path: /etc/unbound/unbound.conf
    state: present
  name: Include blocklist in main config
- ansible.builtin.service:
    name: unbound
    state: restarted
  name: Restart Unbound to apply blocklist
