- ansible.builtin.shell: 'set -o pipefail grep -i query /var/log/unbound/unbound.log
    | awk ''{print $5}'' | sort | uniq -c | sort -nr > /tmp/dns-query-summary.txt

    '
  args:
    executable: /bin/bash
  changed_when: false
  name: Generate DNS query volume summary
- ansible.builtin.slurp:
    src: /tmp/dns-query-summary.txt
  name: Load summary into template var
  register: dns_summary_file
