- ansible.builtin.file:
    group: root
    mode: '0755'
    owner: root
    path: /etc/alertmanager
    state: directory
  name: Create Alertmanager Config Directory
- ansible.builtin.template:
    dest: /etc/alertmanager/alertmanager.yml
    group: root
    mode: '0644'
    owner: root
    src: alertmanager.yml.j2
  name: Deploy Alertmanager Configuration
  notify: Restart Alertmanager
- community.docker.docker_container:
    command: --config.file=/etc/alertmanager/alertmanager.yml
    image: prom/alertmanager:latest
    name: alertmanager
    ports:
    - 9093:9093
    restart_policy: always
    state: started
    volumes:
    - /etc/alertmanager:/etc/alertmanager
  name: Run Alertmanager Container
  register: alertmanager_result
- ansible.builtin.set_fact:
    dummy: true
  name: Mark unchanged if no container changed
  when: not alertmanager_result.changed
- ansible.builtin.debug:
    msg: "\u2705 Alertmanager deployed and running on port 9093"
  name: Print Alertmanager deployment message
