- ansible.builtin.uri:
    body: '{{ lookup(''template'', ''webhook-payload.json.j2'') }}'
    body_format: json
    headers:
      Content-Type: application/json
    method: POST
    status_code: 200
    url: '{{ external_alert_webhook_url }}'
  name: Send alert to external system
