- ansible.builtin.file:
    group: unbound
    mode: '0750'
    owner: unbound
    path: /var/log/unbound
    state: directory
  name: Ensure Log Directory Exists
- ansible.builtin.lineinfile:
    insertafter: '^server:'
    line: '    log-queries: true'
    path: /etc/unbound/unbound.conf
    regexp: '^\s*log-queries:'
    state: present
  name: Configure Unbound for DNS Logging
  notify: Restart Unbound
- ansible.builtin.lineinfile:
    insertafter: '^server:'
    line: '    log-replies: true'
    path: /etc/unbound/unbound.conf
    regexp: '^\s*log-replies:'
    state: present
  name: Configure Unbound to Log Replies
  notify: Restart Unbound
- ansible.builtin.copy:
    dest: /etc/logrotate.d/unbound
    group: root
    mode: '0644'
    owner: root
    src: unbound-logrotate.conf
  name: Set Log Rotation for Unbound Logs
- ansible.builtin.debug:
    msg: "\u2705 DNS query logging enabled for Unbound"
  name: Print DNS logging setup message
