- ansible.builtin.package:
    name: ufw
    state: present
  name: Install UFW
- community.general.ufw:
    name: OpenSSH
    rule: allow
  name: Allow SSH
- community.general.ufw:
    port: 53
    proto: '{{ item }}'
    rule: allow
  loop:
  - tcp
  - udp
  name: Allow DNS (TCP and UDP)
- community.general.ufw:
    port: '{{ item }}'
    rule: allow
  loop:
  - 80
  - 443
  - 9090
  - 3000
  name: Allow Web Interfaces (HTTP, HTTPS, Prometheus, Grafana)
- community.general.ufw:
    from_ip: '{{ item }}'
    rule: allow
  loop:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  name: Allow Internal Access from RFC1918 IP Ranges
- community.general.ufw:
    direction: incoming
    policy: deny
    state: enabled
  name: Set Default Incoming Policy to Deny and Enable UFW
  notify: Reload firewall
- ansible.builtin.command: ufw status verbose
  changed_when: false
  name: Print current firewall status
  register: ufw_status
- ansible.builtin.debug:
    msg: '{{ ufw_status.stdout_lines }}'
  name: Show firewall summary
