null
---
- ansible.builtin.blockinfile:
    block: 'auto-trust-anchor-file: "/var/lib/unbound/root.key"

      val-clean-additional: true

      '
    marker: '# {mark} DNSSEC config'
    path: /etc/unbound/unbound.conf
  name: Configure DNSSEC options in Unbound
- ansible.builtin.service:
    name: unbound
    state: restarted
  name: Restart Unbound to apply DNSSEC settings
