null
---
- ansible.builtin.package:
    name:
    - unbound
    - dnssec-tools
    state: present
  name: Install DNSSEC validation tools
- ansible.builtin.file:
    mode: '0755'
    path: /var/lib/unbound
    state: directory
  name: Ensure Unbound directory exists
- ansible.builtin.command:
    cmd: unbound-anchor -a "/var/lib/unbound/root.key"
  changed_when: false
  name: Fetch root trust anchor
