null
---
- ansible.builtin.file:
    mode: '0755'
    path: /etc/blackbox-exporter
    state: directory
  name: Create uptime Prometheus check config directory
- ansible.builtin.template:
    dest: /etc/systemd/system/uptime-monitor.service
    mode: '0644'
    src: uptime-monitor.service.j2
  name: Deploy uptime check config file
- ansible.builtin.systemd:
    daemon_reload: true
  name: Reload systemd to register uptime monitor
- ansible.builtin.service:
    enabled: true
    name: uptime-monitor
    state: started
  name: Start uptime monitor service
