null
---
- ansible.builtin.template:
    dest: /etc/stubby/stubby.yml
    group: root
    mode: '0644'
    owner: root
    src: stubby.yml.j2
  name: Deploy Stubby configuration
- ansible.builtin.service:
    enabled: true
    name: stubby
    state: restarted
  name: Enable and start stubby service
- ansible.builtin.blockinfile:
    block: "forward-zone:\n  name: \".\"\n  forward-addr: 127.0.0.1@8053\n"
    marker: '# {mark} DoT forward'
    path: /etc/unbound/unbound.conf
  name: Configure Unbound to forward to Stubby
- ansible.builtin.service:
    name: unbound
    state: restarted
  name: Restart Unbound after Stubby setup
