- community.general.mail:
    body: '{{ lookup(''template'', ''status-report.html.j2'') }}'
    host: '{{ smtp_server }}'
    password: '{{ smtp_password }}'
    port: 587
    subject: Weekly DNS & System Status Report
    subtype: html
    to: '{{ report_recipient }}'
    username: '{{ smtp_user }}'
  name: Send HTML report via mail
