- ansible.builtin.package:
    name: fail2ban
    state: present
  name: Install Fail2Ban
- ansible.builtin.template:
    dest: /etc/fail2ban/jail.local
    group: root
    mode: '0644'
    owner: root
    src: jail.local.j2
  name: Deploy Fail2Ban Configuration
  notify: Restart Fail2Ban
- ansible.builtin.service:
    enabled: true
    name: fail2ban
    state: started
  name: Enable and Start Fail2Ban
- ansible.builtin.debug:
    msg: "\u2705 Fail2Ban installed and running"
  name: Print Fail2Ban setup message
