---
- name: Install Fail2Ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Deploy Fail2Ban Configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2Ban

- name: Enable and Start Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Print Fail2Ban setup message
  ansible.builtin.debug:
    msg: "✅ Fail2Ban installed and running"
