- ansible.builtin.file:
    mode: '0755'
    path: /etc/prometheus
    state: directory
  become: true
  name: Create Prometheus configuration directory
- ansible.builtin.template:
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
    src: prometheus.yml.j2
  become: true
  name: Deploy Prometheus configuration
  notify: Restart prometheus
- become: true
  community.docker.docker_container:
    image: prom/prometheus:latest
    name: prometheus
    published_ports:
    - 9090:9090
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes:
    - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  name: Ensure Prometheus is running via Docker
