---
- name: Create Prometheus configuration directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
  become: true

- name: Deploy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  become: true
  notify: Restart prometheus

- name: Ensure Prometheus is running via Docker
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: unless-stopped
    restart: true
    published_ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  become: true
