- ansible.builtin.template:
    dest: /etc/GeoIP.conf
    mode: '0644'
    src: geoip.conf.j2
  name: Copy GeoIP configuration
- ansible.builtin.command:
    cmd: geoipupdate
  changed_when: true
  name: Run geoipupdate
