---
- name: Copy GeoIP configuration
  ansible.builtin.template:
    src: geoip.conf.j2
    dest: /etc/GeoIP.conf
    mode: '0644'

- name: Run geoipupdate
  ansible.builtin.command:
    cmd: geoipupdate
  changed_when: true
