null
--- null
---
- ansible.builtin.template:
    dest: /etc/rsyslog.d/50-dns.conf
    mode: '0644'
    src: rsyslog-dns.conf.j2
  name: Configure rsyslog for DNS query logging
- ansible.builtin.service:
    name: rsyslog
    state: restarted
  name: Restart rsyslog
