null
---
- ansible.builtin.lineinfile:
    insertafter: EOF
    line: 'include: /etc/unbound/rpz.zone'
    path: /etc/unbound/unbound.conf
    regexp: ^include:.*rpz\.zone
  name: Include RPZ in Unbound config
