---
---
name: Ensure PR Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  require-label:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Check for required label
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const requiredLabel = 'release';
          const labels = context.payload.pull_request.labels.map(label => label.name);
          if (!labels.includes(requiredLabel)) {
            core.setFailed(`Missing required label: ${requiredLabel}`);
          }
