name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible + Ansible Lint
        run: |
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint playbook.yml
