---
- name: Ensure Pi-hole config directory exists
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    mode: '0755'
  become: true

- name: Deploy custom host overrides
  ansible.builtin.template:
    src: pihole-custom.list.j2
    dest: /etc/pihole/custom.list
    mode: '0644'
  become: true
  notify: Restart pihole

- name: Run Pi-hole in Docker
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    restart_policy: unless-stopped
    restart: true
    env:
      TZ: "{{ ansible_date_time.tz }}"
      WEBPASSWORD: "{{ vault_pihole_password }}"
    published_ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "80:80"
      - "443:443"
    volumes:
      - /etc/pihole:/etc/pihole
      - /etc/dnsmasq.d:/etc/dnsmasq.d
  become: true
